name: 'Setup SSH'
description: 'Sets up SSH for the runner'
inputs:
  deployment-server-ip:
    description: 'Deployment server IP address'
    required: true
  deployment-server-ssh-private-key:
    description: 'Private SSH key for the deployment server'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install ssh-keyscan
      run: sudo apt-get install -y openssh-client
      shell: bash
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.deployment-server-ssh-private-key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ inputs.deployment-server-ip }} >> ~/.ssh/known_hosts
      shell: bash